### ISSUE TITLE
creat fulfillment error

### ISSUE THREAD

**Issue by zhaofp** [ChannelApe/shopify-sdk#102]
If different fulfillment orders belonging to an order have different delivery_method, you will get an error when creating a fulfillment: {"errors": ["All fulfillment orders must have the same delivery method type. Multiple delivery method types [\" none\ ",\" shipping\ "] were found."]}

**Comment by ryankazokas** [comment]
I'm going to close this out as i haven't heard back and I still haven't encountered the issue myself.  Happy to reopen if it is a widespread issue.
