### ISSUE TITLE
I want to change the inventory

### ISSUE THREAD

**Issue by whoamizq** [ChannelApe/shopify-sdk#118]
But using this method didn't work?
shopifySdk.updateVariant()
![image](https://github.com/ChannelApe/shopify-sdk/assets/60696806/b4014d4d-6cde-4d60-b909-601c3fcced61)

**Comment by dimaloop** [comment]
Is there are any way to GET variant's inventory item levels?

**Comment by ryankazokas** [comment]
When you do a GET to a variant
> getVariant(final String variantId)

The inventory level is an aggregate of the levels across all locations. 

As for this [endpoint](https://shopify.dev/docs/api/admin-rest/2023-04/resources/inventorylevel#get-inventory-levels?location-ids=655441491) , we do not have that functionality yet built in to the sdk.
