### ISSUE TITLE
Support for customer(s) lookup

### ISSUE THREAD

**Issue by brownac** [ChannelApe/shopify-sdk#16]
I noticed that the latest version of the SDK has support for updating customer information. It would be great to have methods called `getCustomers()` and `getCustomer(String id)` or something of that nature that fetch all customers and individual customer details based on an e-mail or an ID. It would also be nice to extend this support to the [customer search endpoint](https://help.shopify.com/en/api/reference/customers/customer#search) in case you need to search for a customer based on some other attribute than ID.

**Comment by brownac** [comment]
(by the way, I'm happy to take this up!)

**Comment by ryankazokas** [comment]
Awesome. Thanks @brownac . PR's are welcome.

**Comment by rjdavis3** [comment]
Thanks for your PR @brownac. Your changes are now part of the 1.6.0-SNAPSHOT. We should be releasing 1.6.0 early next week. Sorry for the delay.

cc: @ryankazokas

**Comment by rjdavis3** [comment]
This has been handled by the [1.6.0](https://github.com/ChannelApe/shopify-sdk/tree/1.6.0) release.
