### ISSUE TITLE
Add Optional API Version Step to Shopify SDK Builder

### ISSUE THREAD

**Issue by rjdavis3** [ChannelApe/shopify-sdk#21]
We do not allow specification of an API version within this SDK right now. This makes it tough when Shopify introduces breaking changes that someone might want to wait to adopt. We should add an optional step to our Shopify SDK Builder that takes in an API version.

https://help.shopify.com/en/api/versioning

**Comment by brownac** [comment]
@rjdavis3 I could take this up if you all still want some help with this!

**Comment by rjdavis3** [comment]
Hi @brownac thanks for wanting to help on this. @ryankazokas and I had some internal discussions around this issue and I think we decided on closing it.

Different endpoints will need to be hard-coded to different versions depending on when it was last updated. Some endpoints like orders are more popular than others like product images so they may be support newer versions faster.

I do not see this as a problem since Shopify will default to the oldest supported API version if we pass up a version in the URL that is no longer supported.

@ryankazokas are you ok with closing this issue or altering it to hard-code API versions into the URLs?

**Comment by ryankazokas** [comment]
@rjdavis3 @brownac yeah. I think it would make the SDK more rigid if we supported only a single API version. I started working on just setting the API versions in the related endpoint constants for orders / products for #20 and that is I think we should move forward. My vote would be to close this issue.
