### ISSUE TITLE
Support Java 9, 10, and 11

### ISSUE THREAD

**Issue by rjdavis3** [ChannelApe/shopify-sdk#31]
shopify-sdk relies on JAXB APIs that were part of the JDK in Java 8 but lost support in later versions. We should ensure that the shopify-sdk works with Java 8, 9, 10, and 11

Hopefully we can accomplish this by just including the Maven Dependencies for JAXB that are now excluded. 

We should start running CI builds with different JDK versions to ensure we maintain support.

https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j

**Comment by ryankazokas** [comment]
@rjdavis3 Yeah i think we can do this. 
We'll have to push to maven with our minimal supported version or it won't work with older projects. 
Compiled with java 11 and pushing to maven will start giving errors on projects that are using earlier versions:
```
com/shopify/ShopifySdk has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Travis actually supports testing multiple JDK's:
https://blog.travis-ci.com/support_for_multiple_jdks/

However we may have to address #13  if we are going to be running the tests against multiple sdks

**Comment by rjdavis3** [comment]
@ryankazokas I would like to run this against multiple JDKs if possible. This way we can ensure we maintain support.

**Comment by rjdavis3** [comment]
https://github.com/ChannelApe/shopify-sdk/releases/tag/2.0.0
