### ISSUE TITLE
Support for private apps

### ISSUE THREAD

**Issue by kennethjor** [ChannelApe/shopify-sdk#37]
Shopify has separate non-oauth authentication for private apps for individual shops. This uses HTTP Basic authentication. The SDK doesn't appear to support this currently.

https://help.shopify.com/en/manual/apps/private-apps

**Comment by ryankazokas** [comment]
@kennethjor private apps can also use the X-Shopify-Access-Token request header which is the admin API password of the private app to auth which this SDK supports:
https://shopify.dev/tutorials/authenticate-a-private-app-with-shopify-admin#make-authenticated-requests

Is there a reason to use HttpBasic over this method? We can look at adding this to the SDK if there is a valid reason, however, I don't want to increase complexity of it if there are no benefits.

**Comment by kennethjor** [comment]
@ryankazokas No reason, I was simply unaware of that authentication method. I guess I stopped reading after "basic auth" :) I've submitted a PR with an extra line in the readme.
