### ISSUE TITLE
createProduct with images

### ISSUE THREAD

**Issue by chandrantwins** [ChannelApe/shopify-sdk#46]
Hi,

Thanks for nice shopify sdk, i need to create product with images in one api call .. is that possible?
https://shopify.dev/docs/admin-api/rest/reference/products/product

because i can see here the sample, but our code do create product seperatly and updateproductimages seperatly.. is there anyway to do in single step.. i mean can we include in create product post api call itself.

Thanks
Chandran

**Comment by ryankazokas** [comment]
@chandrantwins we do have the ability to do this currently. You can provide image sources within the [ProductCreationRequest](https://github.com/ChannelApe/shopify-sdk/blob/master/src/main/java/com/shopify/model/ShopifyProductCreationRequest.java)

`
     public static interface ImageSourcesStep {
		public VariantCreationRequestsStep withImageSources(final List<String> imageSources);
	}
`

**Comment by chandrantwins** [comment]
Hi Ryan,

Thanks for your response, yes i tried it works. Please can i know when is your next release planned
