### ISSUE TITLE
Upgrade to version 2021 - 01

### ISSUE THREAD

**Issue by vitruvvius** [ChannelApe/shopify-sdk#56]
Hi!

I was hoping to support and use this github repository for shop integration - are we expecting that it'll upgrade to 2021 anytime soon?

**Comment by rjdavis3** [comment]
Hi @vitruvvius I think our latest version, [2.3.0](https://github.com/ChannelApe/shopify-sdk/releases/tag/2.3.0) should do what you are requesting.

You can specify an API Version when you are building the SDK.
