### ISSUE TITLE
How many products does getProducts() return?

### ISSUE THREAD

**Issue by charinduedirisuriya** [ChannelApe/shopify-sdk#59]
There is no documentation on how many products will get returned by the getProducts() method.
Does anybody have an idea?

**Comment by ryankazokas** [comment]
If you are calling the getProducts() method, it is going to try get all of the products in your store. It will paginate 50 products at a time until it reaches the last page.

If you want more control of it, we do expose a method to get the first page and subsequent pages with 

```
public ShopifyPage<ShopifyProduct> getProducts(final int pageSize)
```
and subsequent pages

```
public ShopifyPage<ShopifyProduct> getProducts(final String pageInfo, final int pageSize)
```

**Comment by charinduedirisuriya** [comment]
Thank you @ryankazokas
