### ISSUE TITLE
How to download Shopify Report

### ISSUE THREAD

**Issue by heppytt** [ChannelApe/shopify-sdk#82]
There are many reports that can be downloaded in the background of Shopify. How can I download background reports through API, or does this SDK support background report downloading?

**Comment by ryankazokas** [comment]
Currently this sdk does not support report functionality but we are always open to PR submissions to add that support.

**Comment by heppytt** [comment]
Thank you.

**Comment by heppytt** [comment]
> Currently this sdk does not support report functionality but we are always open to PR submissions to add that support.

how to use  PR submissions to add that support？

**Comment by ryankazokas** [comment]
You can fork the repo. Make the changes, and then open a Pull Request in github when you make the changes. Just be sure to follow the contribution guidelines outlined here:

https://github.com/ChannelApe/shopify-sdk/blob/master/CONTRIBUTING.md
