### ISSUE TITLE
why my demo project  reports java.net.UnknownHostException: https?

### ISSUE THREAD

**Issue by jspyth** [ChannelApe/shopify-sdk#84]
when i run code below,my project report exception"java.net.UnknownHostException: https" :
ShopifySdk.newBuilder()
                .withSubdomain("https://store-test.myshopify.com")
                .withAccessToken(accessToken)
                .withMaximumRequestRetryTimeout(5, TimeUnit.SECONDS)
                .withMaximumRequestRetryRandomDelay(5, TimeUnit.SECONDS)
                .build().createProduct(shopifyProductCreationRequest);

**Comment by ryankazokas** [comment]
@jspyth the build will handle adding https:// and myshopify.com pieces. All you should need to add is 'store-test' as the shop subdomain and it should work.

**Comment by jspyth** [comment]
ok，thanks



---- Replied Message ----
| From | Ryan ***@***.***> |
| Date | 05/11/2022 19:33 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [ChannelApe/shopify-sdk] why my demo project reports java.net.UnknownHostException: https? (Issue #84) |

@jspyth the build will handle adding https:// and myshopify.com pieces. All you should need to add is 'store-test' as the shop subdomain and it should work.
