### ISSUE TITLE
Can i get diffrent store products info by one admin token?

### ISSUE THREAD

**Issue by jspyth** [ChannelApe/shopify-sdk#86]
We create two store for diffrent language, if i must to get two store products info  through two admin token and subdomain?

**Comment by ryankazokas** [comment]
Yep, you'd need two separate instances of the sdk. One for each store.

**Comment by jspyth** [comment]
Thanks.



---- Replied Message ----
| From | Ryan ***@***.***> |
| Date | 05/24/2022 19:25 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [ChannelApe/shopify-sdk] Can i get diffrent store products info by one admin token? (Issue #86) |

Yep, you'd need two separate instances of the sdk. One for each store.
